amadeus/urls.py
from django.urls import path
from . import views
app_name = "amadeus"

urlpatterns = [
    path("all_hotels/", views.all_hotels_view, name="all_hotels"),
    path("hotel_detail/<str:hotelId>/", views.hotel_detail_view, name="hotel_detail"),
]

blog/urls.py
from . import views
from django.urls import path
from .views import *
from .api_view import *

app_name = "blog"


urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<slug:slug>", views.post_detail, name="post_detail"),
    # api
    path("api/list", post_list_api, name="post_list_api"),
    path("api/<int:id>", post_detail_api, name="post_detail_api"), 
    path("api/filter/<str:query>", post_search_api, name="post_search_api"),

    path("api/list/api", post_list_apis, name="post_list_api"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path('amadeus/', include('amadeus.urls', namespace="amadeus")),
    path("unit/", include("unit.urls", namespace="unit")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("", include("settings.urls", namespace="settings")),
    path("summernote/", include("django_summernote.urls")),
    path("api/auth/", include("knox.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("rest-auth/", include("dj_rest_auth.urls")),
    # path('rest-auth/registration/',include('dj_rest_auth.registration.urls')),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amadeus/models.py
from django.db import models

# Create your models here.

amadeus/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from .amadues_api import *

def all_hotels_view(request):
    
    city_code = request.GET.get('city_code', 'CAI')
    search_query = request.GET.get('query', '')
    hotels = get_all_hotels(city_code, search_query) 
    page_number = request.GET.get('page', 1) 
    hotels_per_page = 10  
    paginator = Paginator(hotels, hotels_per_page)
    page_obj = paginator.get_page(page_number)
    return render(request, 'hotels/all_hotels.html',
                {
                'hotels': page_obj,
                'query': search_query,
                'city_code': city_code,
                })


def hotel_detail_view(request, hotelId):
  
    city_code = request.GET.get('city_code')  
    hotels = get_all_hotels(city_code)

    hotel = next((hotel for hotel in hotels if hotel["hotelId"] == hotelId), None)

    if hotel:
        return render(request, 'hotels/hotel_detail.html', {'hotel': hotel, 'city_code': city_code})
    else:
        return render(request, 'hotels/hotel_detail.html', {'error': 'Hotel not found.'})

amadeus/templates/hotels/all_hotels.html
{% extends 'main_task.html' %}

{% block body %}
    <div>

        <form method="GET" action="{% url 'amadeus:all_hotels' %}">
            <label for="city"> Select City:</label>
            <select name="city_code" id="city">
                <option value="PAR">Paris</option>
                <option value="NYC">New York</option>
                <option value="LON">London</option>
                <option value="TYO">Tokyo</option>
                <option value="DXB">Dubai</option>
                <option value="ROM">Rome</option>
                <option value="IST">Istanbul</option>
                <option value="BKK">Bangkok</option>
                <option value="SIN">Singapore</option>
                <option value="BCN">Barcelona</option>
                <option value="CAI">Cairo</option>
            </select>
            
            <button type="submit" class="btn palatin-btn">Search</button>
        </form>
        
        <br>
        <form method="GET" action="">
            <input type="text" name="query" placeholder="Search for hotels..." value="{{ query }}" required>
            <button type="submit" class="btn palatin-btn">Search</button>
        </form>
        
        <br>
        {% for hotel in hotels %}
            <li>
                <a href="{% url 'amadeus:hotel_detail' hotelId=hotel.hotelId %}?city_code={{ city_code }}">
                    {{ hotel.name }}
                </a>
            </li>
            <hr>
        {% endfor %}
    </div>
    {% if hotels.has_other_pages %} 
    <div class="col-12">
        <div class="pagination-area wow fadeInUp" data-wow-delay="100ms">
            <nav>
                <ul class="pagination">
                    {% if hotels.number > 2 %}
                        <li class="page-item"><a class="page-link" href="?page=1&city_code={{ city_code }}">First</a></li>
                    {% endif %}
                    
                    {% if hotels.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ hotels.previous_page_number }}&city_code={{ city_code }}">Previous</a></li>
                    {% endif %}
    
                    {% for i in hotels.paginator.page_range %}
                        {% if i >= hotels.number|add:"-1" and i <= hotels.number|add:"1" %}
                            <li class="page-item {% if i == hotels.number %}active{% endif %}">
                                <a class="page-link" href="?page={{ i }}&city_code={{ city_code }}">{{ i }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
    
                    {% if hotels.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ hotels.next_page_number }}&city_code={{ city_code }}">Next</a></li>
                    {% endif %}
                    
                    {% if hotels.number < hotels.paginator.num_pages|add:"-1" %}
                        <li class="page-item"><a class="page-link" href="?page={{ hotels.paginator.num_pages }}&city_code={{ city_code }}">Last</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
    {% endif %}
     
    {% endblock body %}

amadeus/templates/hotels/hotel_detail.html
{% extends 'base_amadeus.html' %}

{% block body %}
<div style="display: flex; justify-content: center; align-items: center; height: 100vh; text-align: center;">
    <div style="max-width: 600px; padding: 20px; border: 1px solid #ccc; border-radius: 10px; background-color: #f9f9f9;">
        {% if hotel %}
            <p>Hotel Name: {{ hotel.name }}</p>
            <p>Address: {{ hotel.address.countryCode }}</p>
            <p>Location: Latitude: {{ hotel.geoCode.latitude }}, Longitude: {{ hotel.geoCode.longitude }}</p>
            <p>ID: {{ hotel.hotelId }}</p>
        {% else %}
            <p>No hotel information available.</p>
        {% endif %}
    </div>
</div>
{% endblock body %}