accounts/urls.py
from django.urls import path, include
from . import views
from .api_views import api_profile


app_name = "accounts"

urlpatterns = [ 
    path("signup", views.sign_up, name="signup"),
    path('logout/', views.log_out, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("reservation", views.my_reservation, name="my_reservation"),
    path("check/<int:id>", views.check_reservation, name="check_reservation"),
    path("cancel/<int:id>", views.cancel_reservation, name="cancel_reservation"),
    path("password/change", views.change_password, name="change_password"),
    # api
    # path("api/profile", api_profile, name="api_profile"),
    path("api/profile", api_profile, name="api_profile"),
]

blog/urls.py
from . import views
from django.urls import path
from .views import *
from .api_view import *

app_name = "blog"


urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<slug:slug>", views.post_detail, name="post_detail"),
    # api
    path("api/list", post_list_api, name="post_list_api"),
    path("api/<int:id>", post_detail_api, name="post_detail_api"), 
    path("api/filter/<str:query>", post_search_api, name="post_search_api"),

    path("api/list/api", post_list_apis, name="post_list_api"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path('amadeus/', include('amadeus.urls', namespace="amadeus")),
    path("unit/", include("unit.urls", namespace="unit")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("", include("settings.urls", namespace="settings")),
    path("summernote/", include("django_summernote.urls")),
    path("api/auth/", include("knox.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("rest-auth/", include("dj_rest_auth.urls")),
    # path('rest-auth/registration/',include('dj_rest_auth.registration.urls')),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unit/urls.py
from . import views
from django.urls import path
from .views import *
from .api_view import *

app_name = "unit"

urlpatterns = [
    path("", views.unit_list, name="unit_list"),
    path("<slug:slug>", views.unit_detail, name="unit_detail"),
    # api
    path("api/", UnitAPIList.as_view(), name="unit_api_list"),
    path("api/<int:pk>", UnitAPIdetail.as_view(), name="unit_api_detail"),
    path(
        "api/create_reservation/",
        CreateReservationAPI.as_view(),
        name="create_reservation_api",
    ),
    path(
        "api/reservation/<int:id>", reservation_detail_api, name="unit_api_reservation"
    ),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Token.objects.create(user=instance)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from .models import *
from django.core.exceptions import ValidationError


class SignupForm(UserCreationForm):
    def clean(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email exists")
        return self.cleaned_data

    class Meta:
        model = User
        email = models.EmailField(unique=True)
        fields = ["username", "email", "password1", "password2"]


class PasswordChangingForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ["old_password", "new_password1", "new_password2"]

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import logout
from .forms import SignupForm, PasswordChangingForm
from django.contrib.auth import login
from .models import *
from unit.models import *
from django.contrib.auth.decorators import login_required


def sign_up(request, backend="django.contrib.auth.backends.ModelBackend"):
    if request.method == "POST":
        form = SignupForm(data=request.POST)
        if form.is_valid():
            use = form.cleaned_data["username"]
            em = form.cleaned_data["email"]
            user = User.objects.create(username=use, email=em)
            user.set_password(form.cleaned_data["password2"])
            user.save()

            if user is not None:
                if user.is_active:
                    login(
                        request,
                        user,
                        backend="django.contrib.auth.backends.ModelBackend",
                    )

                    return redirect("/accounts/profile")
    else:
        form = SignupForm()

    return render(request, "accounts/sign_up.html", {"form": form})


@login_required
def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request, "accounts/profile.html", {"profile": profile})


@login_required
def my_reservation(request):
    unit_list = UnitBook.objects.filter(user=request.user)
    if len(unit_list) > 0:
        return render(request, "accounts/reservations.html", {"unit_list": unit_list})
    else:
        make_reservation = "You don't have any reservation yet"
        return render(
            request,
            "accounts/reservations.html",
            {"make_reservation": make_reservation},
        )


def check_reservation(request, id):
    check_book = UnitBook.objects.get(id=id)
    return render(
        request, "accounts/check_reservation.html", {"check_book": check_book}
    )


def cancel_reservation(request, id):
    cancel_book = UnitBook.objects.get(id=id)
    cancel_book.delete()
    return redirect("/accounts/reservation")


def change_password(request):
    if request.method == "post":
        form = PasswordChangingForm(user=request.user)
        if form.is_valid():
            user = request.user
            user.set_password(form.cleaned_data["new_password2"])
            user.save()
    else:
        form = PasswordChangingForm(user=request.user)

    return render(request, "registration/password_change_form.html", {"form": form})


def log_out(request):
    logout(request)
    return redirect("/")

accounts/templates/accounts/check_reservation.html
{% extends 'base.html' %}
{% load static %}
{% block body %}



<body>
    <!-- ##### Breadcumb Area Start ##### -->
    <section class="breadcumb-area bg-img d-flex align-items-center justify-content-center" style="background-image: url({% static 'img/bg-img/bg-7.jpg' %});">
        <div class="bradcumbContent">
            <h2>Reservations</h2>
        </div>
    </section>
    <!-- ##### Breadcumb Area End ##### -->

    <!-- ##### Book Now Area Start ##### -->
    <div class="book-now-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-lg-14">
                    <div class="book-now-form">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Book Now Area End ##### -->

    <!-- ##### Blog Area Start ##### -->
    <div class="blog-area section-padding-0-100">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="palatin-blog-posts">

                        <!-- ##### Single Blog Post ##### -->
                        <div class="single-blog-post mb-100 wow fadeInUp" data-wow-delay="100ms">
                            <!-- Post Thumb -->
                            <div class="blog-post-thumb">
                                <img src="{{check_book.unit.image.url}}" alt="">
                            </div>
                            <!-- Post Content -->
                            <div class="post-content">
                                <!-- Post Date-->
                                <h2>Unit name : {{check_book.unit.name}}</h2>
                                <h4>Reservation created at : {{check_book.created_at.date}}.</h4>
                                <h4>Reservation start : {{check_book.date_from}}.</h4>
                                <h4>Reservation end : {{check_book.date_to}}.</h4>
                                <div class="post-meta d-flex justify-content-center">
                                   
                                </div>
                                <a href="{%url 'accounts:cancel_reservation' check_book.id %}" class="book-room-btn btn palatin-btn">Cancel reservation</a>
                            </div>
                        </div>



                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Blog Area End ##### -->
</body>
{% endblock body %}

accounts/templates/accounts/profile.html

{% extends 'base.html' %}
{% load static %}
{% block body %}


    <!-- ##### Breadcumb Area Start ##### -->
    <section class="breadcumb-area bg-img d-flex align-items-center justify-content-center" style="background-image: url({%static 'img/bg-img/bg-8.jpg'%});">
        <div class="bradcumbContent">
            <h2>Profile</h2>
        </div>
    </section>
    <!-- ##### Breadcumb Area End ##### -->

    <!-- ##### Book Now Area Start ##### -->
    <div class="book-now-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-lg-10">
                    <div class="book-now-form">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Book Now Area End ##### -->

    <!-- ##### Contact Area Start ##### -->
    <section class="contact-information-area">
        <div class="container">
            <div class="row">

                <!-- Single Contact Information -->
                <div class="col-12 col-lg-4">
                    <div class="single-contact-information mb-100">
                        <div class="section-text">
                            <h3>{{settings.address}}</h3>
                            <p>We hope your experience with us will be pleasant.</p>
                        </div>
                        <!-- Single Contact Information -->

                        <!-- Single Contact Information -->
                        <!-- Single Contact Information -->
                        <div class="contact-content d-flex">
                            <p>E-mail</p>
                            <p>{{profile.user.email}}</p>
                        </div>
                    </div>
                </div>

        </div>
    </section>
    <!-- ##### Contact Area End ##### -->

    <!-- ##### Contact Form Area Start ##### -->
    <section class="contact-form-area mb-100">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading">
                        <div class="line-"></div>
                        <h2>Wellcome {{profile.user.username}}</h2> 
                    </div>
                    <a href="{% url 'logout' %}" class="btn palatin-btn mt-50" >Logout </a>
                    <a href="{% url 'password_change' %}" class="btn palatin-btn mt-50" >Change Password </a>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                </div>
            </div>
        </div>
    </section>

{% endblock body %}

accounts/templates/accounts/reservation.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<body>
    <!-- Preloader -->
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="cssload-container">
            <div class="cssload-loading"><i></i><i></i><i></i><i></i></div>
        </div>
    </div>



    <!-- ##### Breadcumb Area Start ##### -->
    <section class="breadcumb-area bg-img d-flex align-items-center justify-content-center" style="background-image: url({% static 'img/bg-img/bg-6.jpg' %});">
        <div class="bradcumbContent">
            <h2>Rooms</h2>
        </div>
    </section>
    <!-- ##### Breadcumb Area End ##### -->

    <!-- ##### Book Now Area Start ##### -->
    <div class="book-now-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-lg-10">
                    <div class="book-now-form">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Book Now Area End ##### -->

    <!-- ##### Rooms Area Start ##### -->
    <section class="rooms-area section-padding-0-100">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-lg-6">
                    <div class="section-heading text-center">
                        <div class="line-"></div>
                        <h2>Choose a room</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris sceleri sque, at rutrum nulla dictum. Ut ac ligula sapien.</p>
                    </div>
                </div>
            </div>

            <div class="row">

                <!-- Single Rooms Area -->
            {% for unit in unit_list %}
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="single-rooms-area wow fadeInUp" data-wow-delay="100ms">
                        <!-- Thumbnail -->
                        <div class="bg-thumbnail bg-img" style="background-image: url({{unit.unit.image.url}});"></div>
                        <!-- Price -->
                        <p class="price-from">From ${{unit.unit.price}}/night</p>
                        <!-- Rooms Text -->
                        <div class="rooms-text">
                            <div class="line"></div>
                            <h4>{{unit.unit.name}}</h4>
                            <p>{{unit.unit.description|safe|truncatewords:2}}.</p>
                        </div>
                        <!-- Book Room -->
                        <a href="{{unit.unit.get_absolute_url}}" class="book-room-btn btn palatin-btn">Check reservation</a>
                    </div>
                </div>

            {% endfor %}
                

            </div>
        </div>
    </section>
    <!-- ##### Rooms Area End ##### -->


</body>


{% endblock body %}

accounts/templates/accounts/reservations.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block body %}
<body>
    <!-- Preloader -->
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="cssload-container">
            <div class="cssload-loading"><i></i><i></i><i></i><i></i></div>
        </div>
    </div>



    <!-- ##### Breadcumb Area Start ##### -->
    <section class="breadcumb-area bg-img d-flex align-items-center justify-content-center" style="background-image: url({% static 'img/bg-img/bg-6.jpg' %});">
        <div class="bradcumbContent">
            <h2>Reservation</h2>
        </div>
    </section>
    <!-- ##### Breadcumb Area End ##### -->

    <!-- ##### Book Now Area Start ##### -->
    <div class="book-now-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-lg-10">
                    <div class="book-now-form">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Book Now Area End ##### -->
    
    <!-- ##### Rooms Area Start ##### -->
    <section class="rooms-area section-padding-0-100">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-lg-6">
                    <div class="section-heading text-center">
                        <div class="line-"></div>
                       
                    </div>
                 
                </div>
            </div>

            <div class="row">

                <!-- Single Rooms Area -->
        

        {% if make_reservation %}

        <div class="section-heading text-center">
            <div class="line-"></div>
            <h2>{{make_reservation}}</h2>
            <a href="{%url 'unit:unit_list'  %}" class="book-room-btn btn palatin-btn"> Book Now </a>
        </div>
     

        {% else %}
            {% for unit in unit_list %}
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="single-rooms-area wow fadeInUp" data-wow-delay="100ms">
                        <!-- Thumbnail -->
                        <div class="bg-thumbnail bg-img" style="background-image: url({{unit.unit.image.url}});"></div>
                        <!-- Price -->
                        <p class="price-from">From ${{unit.unit.price}}/night</p>
                        <!-- Rooms Text -->
                        <div class="rooms-text">
                            <div class="line"></div>
                            <h4>{{unit.unit.name}}</h4>
                            <p>{{unit.unit.description|safe|truncatewords:2}}.</p>
                        </div>
                        <!-- Book Room -->
                        <a href="{%url 'accounts:check_reservation' unit.id %}" class="book-room-btn btn palatin-btn">Check reservation</a>
                    </div>
                </div>

            {% endfor %}
            {% endif %}

            </div>
        </div>
    </section>
    <!-- ##### Rooms Area End ##### -->


</body>


{% endblock body %}

accounts/templates/accounts/sginup.html
{% extends "base_generic.html" %}
{% load bootstrap4 %}

{% block h2 %}  
<h2>Sgin Up </h2>        
{% endblock h2 %}


{% block contant%}


<div class="col-12 col-lg-6">
  <form  method="POST" >
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit"  class="btn palatin-btn mt-50" value="sgin up">


  </form>
</div>


{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends "base_generic.html" %}
{% load bootstrap4 %}

{% block h2 %}  
<h2>Sgin Up </h2>        
{% endblock h2 %}


{% block contant%}


<div class="col-12 col-lg-6">
  <form  method="POST" >
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit"  class="btn palatin-btn mt-50" value="sgin up">


  </form>
</div>


{% endblock %}