accounts/urls.py
from django.urls import path, include
from . import views
from .api_views import api_profile


app_name = "accounts"

urlpatterns = [ 
    path("signup", views.sign_up, name="signup"),
    path('logout/', views.log_out, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("reservation", views.my_reservation, name="my_reservation"),
    path("check/<int:id>", views.check_reservation, name="check_reservation"),
    path("cancel/<int:id>", views.cancel_reservation, name="cancel_reservation"),
    path("password/change", views.change_password, name="change_password"),
    # api
    # path("api/profile", api_profile, name="api_profile"),
    path("api/profile", api_profile, name="api_profile"),
]

amadeus/urls.py
from django.urls import path
from . import views
app_name = "amadeus"

urlpatterns = [
    path("all_hotels/", views.all_hotels_view, name="all_hotels"),
    path("hotel_detail/<str:hotelId>/", views.hotel_detail_view, name="hotel_detail"),
]

blog/urls.py
from . import views
from django.urls import path
from .views import *
from .api_view import *

app_name = "blog"


urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<slug:slug>", views.post_detail, name="post_detail"),
    # api
    path("api/list", post_list_api, name="post_list_api"),
    path("api/<int:id>", post_detail_api, name="post_detail_api"), 
    path("api/filter/<str:query>", post_search_api, name="post_search_api"),

    path("api/list/api", post_list_apis, name="post_list_api"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path('amadeus/', include('amadeus.urls', namespace="amadeus")),
    path("unit/", include("unit.urls", namespace="unit")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("", include("settings.urls", namespace="settings")),
    path("summernote/", include("django_summernote.urls")),
    path("api/auth/", include("knox.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("rest-auth/", include("dj_rest_auth.urls")),
    # path('rest-auth/registration/',include('dj_rest_auth.registration.urls')),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from .views import *
from . import views


app_name = "settings"

urlpatterns = [
    path("", views.home, name="home"),
    path("services", views.services, name="services"),
    path("about_us", views.about_us, name="about_us"),
]

unit/urls.py
from . import views
from django.urls import path
from .views import *
from .api_view import *

app_name = "unit"

urlpatterns = [
    path("", views.unit_list, name="unit_list"),
    path("<slug:slug>", views.unit_detail, name="unit_detail"),
    # api
    path("api/", UnitAPIList.as_view(), name="unit_api_list"),
    path("api/<int:pk>", UnitAPIdetail.as_view(), name="unit_api_detail"),
    path(
        "api/create_reservation/",
        CreateReservationAPI.as_view(),
        name="create_reservation_api",
    ),
    path(
        "api/reservation/<int:id>", reservation_detail_api, name="unit_api_reservation"
    ),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>{{my_footer.site_name}}</title>

    <!-- Favicon -->
    <link rel="icon" href="{{my_footer.logo.url}}">

    <!-- Core Stylesheet -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>

<body>


    <!-- ##### Header Area Start ##### -->
    <header class="header-area">
        <!-- Navbar Area -->
        <div class="palatin-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Menu -->
                    <nav class="classy-navbar justify-content-between" id="palatinNav">

                        <!-- Nav brand -->
                        <a href="{%url 'settings:home' %}" class="nav-brand"><img src="{{my_footer.logo.url}}" alt="My image"><p>Booking</p></a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">

                            <!-- close btn -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>

                            <!-- Nav Start -->
                            <div class="classynav">
                                <ul>
                                    
                                    <li class="active"><a href="{%url 'settings:home' %}">Home</a></li>
                                    <li><a href="{%url 'unit:unit_list' %}">Rooms</a></li>
                                    <li><a href="{%url 'accounts:profile'%}">Profile</a></li>
                                    <li><a href="{%url 'accounts:my_reservation'%}">My Reservation</a></li>
                                    <li><a href="#">Pages</a>
                                        <ul class="dropdown">
                                            <li><a href="{%url 'blog:post_list' %}">Blogs</a></li>
                                            <li><a href="{%url 'settings:about_us'%}">About Us</a></li>
                                            <li><a href="{%url 'settings:services'%}">Services</a></li>
                                            <li><a href="{%url 'amadeus:all_hotels'%}">Hotels</a></li>
                                            <li><a href="https://documenter.getpostman.com/view/29351287/2s9Y5cuLum">API Documantation</a></li> 
                                        </ul>
                                    </li>
                                {% if request.user.is_authenticated %}      
                                {% else %}
                                    <li><a href="{%url 'login'%}">Login</a></li>               
                                {% endif %}
                                </ul>

                                <!-- Button -->
                                <div class="menu-btn">
                                    <a href="{%url 'unit:unit_list' %}" class="btn palatin-btn">Make a Reservation</a>
                                </div>

                                
                                
                            </div>
                            <!-- Nav End -->
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ##### Header Area End ##### -->

    {% block body %}
    {% endblock body %}

    <!-- ##### Footer Area Start ##### -->
    <footer class="footer-area">
        <div class="container">
            <div class="row">

                <!-- Footer Widget Area -->
                <div class="col-12 col-lg-5">
                    <div class="footer-widget-area mt-50">
                        <a href="{%url 'settings:home' %}" class="d-block mb-5"><img src="{{my_footer.logo.url}}" alt=""><p>Booking</p></a>
                        <p>We are an international room and villa reservation company. We have a private hotel group that aims to make you happy.
                            More than 50,000 employees are ready to avoid disturbing you during your vacation. </p>
                    </div>
                </div>

                <!-- Footer Widget Area -->
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="footer-widget-area mt-50">
                        <h6 class="widget-title mb-5">Find us on the map</h6>
                        <img src="{%static 'img/bg-img/footer-map.png' %}" alt="">
                    </div>
                </div>

                <!-- Footer Widget Area -->
                <div class="col-12 col-md-6 col-lg-3">
                    <div class="footer-widget-area mt-50">
                        <h6 class="widget-title mb-5">Subscribe to our newsletter</h6>
                        <form action="#" method="post" class="subscribe-form">
                            <input type="email" name="subscribe-email" id="subscribeemail" placeholder="Your E-mail">
                            <button type="submit">Subscribe</button>
                        </form>
                    </div>
                </div>

                <!-- Copywrite Text -->
                <div class="col-12">
                    <div class="copywrite-text mt-30">
                        <p><a href="#"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->

    <!-- ##### All Javascript Script ##### -->
    <!-- jQuery-2.2.4 js -->
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script src="{% static 'js/plugins/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>
</body>

</html>

templates/base_amadeus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>{{my_footer.site_name}}</title>

    <!-- Favicon -->
    <link rel="icon" href="{{my_footer.logo.url}}">

    <!-- Core Stylesheet -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>

<body>


    <!-- ##### Header Area Start ##### -->
    <header class="header-area">
        <!-- Navbar Area -->
        <div class="palatin-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Menu -->
                    <nav class="classy-navbar justify-content-between" id="palatinNav">

                        <!-- Nav brand -->
                        <a href="{%url 'settings:home' %}" class="nav-brand"><img src="{{my_footer.logo.url}}" alt="My image"><p>Booking</p></a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">

                            <!-- close btn -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>

                            <!-- Nav Start -->
                            <div class="classynav">
                                <ul>
                                    
                                    <li class="active"><a href="{%url 'settings:home' %}">Home</a></li>
                                    <li><a href="{%url 'unit:unit_list' %}">Rooms</a></li>
                                    <li><a href="{%url 'accounts:profile'%}">Profile</a></li>
                                    <li><a href="{%url 'accounts:my_reservation'%}">My Reservation</a></li>
                                    <li><a href="#">Pages</a>
                                        <ul class="dropdown">
                                            <li><a href="{%url 'blog:post_list' %}">Blogs</a></li>
                                            <li><a href="{%url 'settings:about_us'%}">About Us</a></li>
                                            <li><a href="{%url 'settings:services'%}">Services</a></li>
                                            <li><a href="{%url 'amadeus:all_hotels'%}">Hotels</a></li>
                                            <li><a href="https://documenter.getpostman.com/view/29351287/2s9Y5cuLum">API Documantation</a></li> 
                                        </ul>
                                    </li>
                                {% if request.user.is_authenticated %}      
                                {% else %}
                                    <li><a href="{%url 'login'%}">Login</a></li>               
                                {% endif %}
                                </ul>

                                <!-- Button -->
                                <div class="menu-btn">
                                    <a href="{%url 'unit:unit_list' %}" class="btn palatin-btn">Make a Reservation</a>
                                </div>
                                
                                
                                
                            </div>
                            <!-- Nav End -->
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ##### Header Area End ##### -->

    {% block body %}
    {% endblock body %}

    <!-- ##### Footer Area Start ##### -->
   
    <!-- ##### Footer Area End ##### -->

    <!-- ##### All Javascript Script ##### -->
    <!-- jQuery-2.2.4 js -->
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script src="{% static 'js/plugins/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>
</body>

</html>

templates/base_generic.html

{% extends 'base.html' %}
{% load static %}
{% block body %}


    <!-- ##### Breadcumb Area Start ##### -->
    <section class="breadcumb-area bg-img d-flex align-items-center justify-content-center" style="background-image: url({%static 'img/bg-img/bg-8.jpg'%});">
        <div class="bradcumbContent">
          {% block h2 %}  
            
          {% endblock h2 %}
        </div>
    </section>
    <!-- ##### Breadcumb Area End ##### -->

    <!-- ##### Book Now Area Start ##### -->
    <div class="book-now-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-lg-10">
                    <div class="book-now-form">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Book Now Area End ##### -->
    <!-- ##### Contact Area Start ##### -->
    <section class="contact-information-area">
        <div class="container">
            <div class="row">

                <!-- Single Contact Information -->
                <div class="col-12 col-lg-4">
                </div>

        </div>
    </section>
    <!-- ##### Contact Area End ##### -->

    <!-- ##### Contact Form Area Start ##### -->
    <section class="contact-form-area mb-100">
        <div class="container">

            <div class="row">
                <div class="col-12">
                    <!-- Contact Form -->
                     {% block contant %}

                     {% endblock contant %}
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Contact Form Area End ##### -->





{% endblock body %}

templates/main_task.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>{{my_footer.site_name}}</title>

    <!-- Favicon -->
    <link rel="icon" href="{{my_footer.logo.url}}">

    <!-- Core Stylesheet -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>

<body>


    <!-- ##### Header Area Start ##### -->
    
    <!-- ##### Header Area End ##### -->

    {% block body %}
    {% endblock body %}

    <!-- ##### Footer Area Start ##### -->
   
    <!-- ##### Footer Area End ##### -->

    <!-- ##### All Javascript Script ##### -->
    <!-- jQuery-2.2.4 js -->
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script src="{% static 'js/plugins/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>
</body>

</html>